- .appveyor.yml
- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
and addded PackageIconUrl for compatibility.
> (GH-10) switched appveyor image VS 2019 

- .github/workflows/publishDocs.yml
- CODE_OF_CONDUCT.md
- README.md
> (GH-15) Updated README and CODE_OF_CONDUCT

- src/Cake.AsciiDoctorJ/AsciiDoctorJAliases.cs
- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
(and fixed the warning)
fixes #17
> (GH-17) added Cake.Addin.Analyzer and CakeContrib.Guidelines

- recipe.cake
- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
- src/stylecop.json
Bumped CakeContrib.Guidelines to version 0.4.0
> (maint) Bumped Cake.Recipe to stable version 2.0.0

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
to work around https://github.com/cake-contrib/Cake.Recipe/issues/724
> (maint) gh-action: set ACTIONS_ALLOW_UNSECURE_COMMANDS

- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
Fix project URL in NuGet package
> Fix project URL

- .github/workflows/publishDocs.yml
- .gitignore
> (GH-68) set the version of actions/checkout to v2

- src/Cake.AsciiDoctorJ/Namespaces.cs
> (GH-69) documented the Namespace

- src/Cake.AsciiDoctorJ.Tests/Cake.AsciiDoctorJ.Tests.csproj
- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
> (GH-72) bumped Cake to 1.0.0

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publishDocs.yml
> (GH-86) updated gh-builds to best practices

- GitReleaseManager.yaml
> (GH-84) updated GRM config

- .github/workflows/codeql-analysis.yml
- .github/workflows/publishDocs.yml
> (GH-95) fixed codeql-analysis

- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
this will also update the logo and fix #98
> (GH-98) updated CakeContrib.Guidelines

- docs/input/_Bottom.cshtml
- docs/input/assets/css/override.less
I've added the buttons and some css.
> Issue #112: GitHub and discussion-buttons

- src/Cake.AsciiDoctorJ/Cake.AsciiDoctorJ.csproj
This solves Issue #114 
Added required settings in csproj-file
> Issue #114 : changed csproj-file, added readme setttings

- README.md
> (#130) replaced appVeyor badge with GH-Actions

- .config/dotnet-tools.json
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publishDocs.yml
- build.ps1
- build.sh
- recipe.cake
according to https://cake-contrib.github.io/Cake.Recipe/docs/upgrading/2.x-to-3.x
> (maint) pinned to Cake 1.3.0 and bumped Cake.recipe to 3

- src/Cake.AsciiDoctorJ.Tests/SettingsExtensionsTests.cs
- src/Cake.AsciiDoctorJ.Tests/SettingsTests.cs
- src/Cake.AsciiDoctorJ/AsciiDoctorJRunnerSettings.cs
- src/Cake.AsciiDoctorJ/AsciiDoctorJRunnerSettingsExtensions.cs
So that required extension libraries can be added via that parameter.
fixes #194
> (#194) changed Require parameter to strings List

- recipe.cake
> (#277) disable codecov

- recipe.cake
> (#361) Update GRM to 0.18.0
